<DOCTYPE HTML>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <title>Visualize your interactome</title>
    <% 
      root = h.url_for( '/' )
                    %>

    <!--<script type="text/javascript"
src="/static/scripts/libs/jquery/jquery.js"></script>-->

    ${h.js('libs/jquery/jquery')}
    ${h.stylesheet_link( root + 'plugins/visualizations/visualize_interactome/static/css/style.css' )}
    ${h.stylesheet_link( root + 'plugins/visualizations/visualize_interactome/static/css/font-awesome-4.0.3/css/font-awesome.css' )}
    ${h.stylesheet_link( root + 'plugins/visualizations/visualize_interactome/static/css/cytoscape.js-panzoom.css' )}
    ${h.stylesheet_link( root + 'plugins/visualizations/visualize_interactome/static/css/jquery.qtip.css' )}
    ${h.javascript_link( root + 'plugins/visualizations/visualize_interactome/static/js/cytoscape.min.js' )}
    ${h.javascript_link( root + 'plugins/visualizations/visualize_interactome/static/js/cytoscape-panzoom.js' )}
    ${h.javascript_link( root + 'plugins/visualizations/visualize_interactome/static/js/jquery.qtip.js' )}
    ${h.javascript_link( root + 'plugins/visualizations/visualize_interactome/static/js/script.js' )}
    ${h.javascript_link( root + 'plugins/visualizations/visualize_interactome/static/js/cytoscape-qtip.js' )}

  </head>

  ## ----------------------------------------------------------------------------
  <body>

    <!-- cy div where the graph generated by CytoscapeJS will appear-->
    <div id="cy"></div>

    <!-- config div for user changeable parameters on the cytoscape graph -->
    <div id="config" class="config">

      <!-- Select Pathway dynamically generated bar-->
      <select name="selectPathway" id="selectPathway" onclick="selectPathway()">
      <option value="all" selected>Choose a pathway</option>
      </select>
      
      <!-- Change graph layout -->
      <select name="select" id="selectShape" onclick="changeLayout()">
        <option value="random">Change Graph Layout</option>
        <option
                value="random">random</option>
        <option
                value="circle">circle</option>
        <option
                value="grid">grid</option>
        <option
                value="concentric" selected>concentric</option>
        <option
                value="breadthfirst">breadthfirst</option>
      </select>
      <!-- Restore graph to its initial form -->
      <button type="button" onclick="getGeneralView()">Global View</button>
      <!-- Focus on a selected node --> 
      <button type="button" onclick="viewSelectedNode()">Node-centric View</button>
      <!-- Search bar for a node -->
      <input type="search" id="search" placeholder="Search Protein" onkeydown="searchProt(event)">  
      
      <!-- Filter the graph by node degree -->
      <input type="search" id="filterdegree" placeholder="Filter proteins with degree >= ..." onkeydown="showNodeWithDegree(event)">  
      
      
     <!-- Display edges interaction score and affect graph edges display-->
      <form id="scoreform" oninput="scoreoutput.value = myScore.value;">  
      
        Score
      <input type="range" name="myScore" id="myScore" max="1" min="0" value="1" step="0.001" onclick="scoreImpact()">
        <output name="scoreoutput"></output>
      </form>

      <!-- Camera icon button to output a png image of the graph -->
      <div id="photo" class="photo">
      <button type="button" onclick="getPNG()"><img src="./static/img/appphoto.png" title="Get a PNG screenshot" width="50px"/></button>
      </div>



      <script>

    // once HTML page has been loaded

		$(document).ready(function() {
		

      // get information on the dataset the visualization is applied on
		  var hdaExt = '${hda.ext}';
		
		  var hdaName = '${ hda.name | h }';
		  var hdaId = '${trans.security.encode_id( hda.id )}';
		  var rawUrl = '${h.url_for( controller="/datasets", action="index" )}';
		  var apiUrl = '${h.url_for( "/" ) + "api/datasets"}';
		
		  var dataUrl = rawUrl + '/' + hdaId + '/display?to_ext=txt';
		
		  // if dataset format is json then proceed to create the network 
      if (hdaExt == "json"){
		    $.ajax(dataUrl, {dataType : 'json', success : function(data){createNetwork(data,hdaExt) }});
		  }
		
		
		
		});
      </script>

  </body>

</html>
